modules/accounts/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
import views
import restaurateur_views

urlpatterns = patterns('',
    url(r'^register/$', views.RegisterView.as_view(), name="register"),
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name="logout"),
    
    url(r'^manage/$', views.ManagerView.as_view(), name="manage_account"),
    url(r'^dashboard/$', views.DashboardView.as_view(), name="dashboard"),
    url(r'^delete/(?P<pk>\d+)/$', views.DeleteUserView.as_view(), name="delete_account"),
    
    url(r'^restaurateurs/create/$', restaurateur_views.CreateRestaurateurView.as_view(), name="restaurateurs_create"),
    url(r'^restaurateurs/(?P<pk>\d+)/manage/$', restaurateur_views.ManageRestaurateurView.as_view(), name="restaurateurs_manage"),
    url(r'^restaurateurs/(?P<pk>\d+)/delete/$', restaurateur_views.DeleteRestaurateurView.as_view(), name="restaurateurs_delete"),
    url(r'^restaurateurs/list/$', restaurateur_views.RestaurateurListView.as_view(), name="restaurateurs_list"),
)

urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.contrib import admin

import views

urlpatterns = patterns('',
	url(r'^$', views.HomeView.as_view(), name="home"),
	url(r'^admin/', include(admin.site.urls)), # Utile dans quelques rare cas
	url(r'^accounts/', include('accounts.urls', namespace="accounts")),
	url(r'^orders/', include('orders.urls', namespace="orders")),
    url(r'^restaurant/', include('restaurant.urls', namespace="restaurant")),
    url(r'^select_language/(?P<lang_code>\w+)/$', views.SelectLanguageView.as_view(), name="select_language"),
    url(r'^about/', views.TemplateView.as_view(template_name="about.html"), name="about"),
    url(r'^webservice/', include('webservice.urls', namespace="webservice")),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

modules/accounts/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django_countries.fields import CountryField
from django.utils.translation import ugettext_lazy as _

class UserDetails(models.Model):
    user = models.OneToOneField(User, verbose_name=_("user"))
    birthdate = models.DateField(verbose_name=_("birth date"))
    tel = models.CharField(max_length=30, verbose_name=_("telephone"))
    country = CountryField(verbose_name=_("country"))
    region = models.CharField(max_length=250, verbose_name=_("province/state/region"))
    city = models.CharField(max_length=250, verbose_name=_("city"))
    address1 = models.CharField(max_length=250, verbose_name=_("address 1"))
    address2 = models.CharField(max_length=250, null=True, blank=True, verbose_name=_("address 2"))
    zip = models.CharField(max_length=10, verbose_name=_("zip code"))
    consent_cp = models.BooleanField(verbose_name=_("I agree to the Terms of Use, EULA and Privacy Policy"))
    
    def get_default_redirect(self):
        """
        Retourne la page vers laquelle l'utilisateur doit être rediriger selon
        sont type de compte.
        """
        if self.is_an_entrepreneur() or self.is_a_restaurateur() or self.is_a_delivery_man():
            redirect_to = reverse('accounts:dashboard')
        else:
            redirect_to = reverse('restaurant:restaurants')
            
        return redirect_to
        
    def is_an_entrepreneur(self):
        """
        Retourne VRAI si l'utilisateur est un entrepreneur.
        """
        return self.user.groups.filter(name='Entrepreneur').exists()
        
    def is_a_restaurateur(self):
        """
        Retourne VRAI si l'utilisateur est un restaurateur.
        """
        return self.user.groups.filter(name='Restaurateur').exists()
        
    def is_a_client(self):
        """
        Retourne VRAI si l'utilisateur est un client.
        """
        return self.user.groups.filter(name='Client').exists()
        
    def is_a_delivery_man(self):
        """
        Retourne VRAI si l'utilisateur est un livreur.
        """
        return self.user.groups.filter(name='Delivery man').exists()
    
    class Meta:
         app_label = 'accounts'
        
class UserAddress(models.Model):
    user = models.ForeignKey(User, verbose_name=_("user"))
    default = models.BooleanField(verbose_name=_("default delivery Address"))
    country = CountryField(verbose_name=_("country"))
    region = models.CharField(max_length=250, verbose_name=_("province/state/region"))
    city = models.CharField(max_length=250, verbose_name=_("city"))
    address1 = models.CharField(max_length=250, verbose_name=_("address 1"))
    address2 = models.CharField(max_length=250, null=True, blank=True, verbose_name=_("address 2"))
    zip = models.CharField(max_length=10, verbose_name=_("zip code"))
    
    class Meta:
         app_label = 'accounts'
    

modules/accounts/forms.py
# -*- coding: utf-8 -*-

import os

from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm, UserCreationForm
from django.contrib.auth.models import User
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django.utils.translation import get_language, ugettext_lazy as _

from crispy_forms.helper import FormHelper
from crispy_forms.layout import HTML, Layout, Submit, Button

from models import UserAddress, UserDetails
from restaurant.models import Restaurant
        
class LoginForm(AuthenticationForm):
    # Formulaire de connexion des utilisateurs
    
    def __init__(self, request=None, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

        self.fields['username'].label = _("Email address")
    
    def clean_username(self):
        """
        Vérifie que l'adresse courriel saisie est valide. Sinon une erreur est levée.
        """
        username = self.data['username']
        
        try:
            validate_email(username)
                
        except ValidationError:
            forms.ValidationError(_("Invalid email address"))
        
        return username
        
class AbstractUserCreationForm(UserCreationForm):
    # Formulaire abstrait de création d'un utilisateur.
    
    class Meta:
        model = User
        fields = ("first_name", "last_name", "email")
        
    def __init__(self, *args, **kwargs):
        super(AbstractUserCreationForm, self).__init__(*args, **kwargs)
        
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['email'].required = True
        
    def clean_email(self):
        """
        Vérifie que l'adresse courriel saisie est valide et unique.
        Sinon une erreur est levée.
        """
        email = self.cleaned_data['email']
        
        users = User.objects.filter(email=email).count()
        if users > 0:
            raise forms.ValidationError(_("The email address you entered is already in use on another account"))
        
        return email
        
    def save(self, commit=True):
        """
        Enregistre le nouvel utilisateur.
        """
        instance = super(AbstractUserCreationForm, self).save(commit=False)
        
        # Il faut obligatoirement mettre un username pour que le modèle de base
        # de Django fonctionne alors on copie simplement l'adresse courriel.
        instance.username = self.cleaned_data['email']
        if commit:
            instance.save()
        return instance
        
class AbstractUserChangeForm(forms.ModelForm):
    # Formulaire abstrait de modification d'un utilisateur.
    
    class Meta:
        model = User
        fields = ("first_name", "last_name", "email")
        
    def __init__(self, *args, **kwargs):
        super(AbstractUserChangeForm, self).__init__(*args, **kwargs)
        
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['email'].required = True
        
    def save(self, commit=True):
        """
        Enregistre le nouvel utilisateur.
        """
        instance = super(AbstractUserChangeForm, self).save(commit=False)
        
        # Il faut obligatoirement mettre un username pour que le modèle de base
        # de Django fonctionne alors on copie simplement l'adresse courriel.
        instance.username = self.cleaned_data['email']
        if commit:
            instance.save()
        return instance

class RegistrationForm(AbstractUserCreationForm):
    # Formulaire concret de création d'un utilisateur.
    
    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout('first_name', 'last_name', 'email', 'password1', 'password2')
    
class RegistrationDetailsForm(forms.ModelForm):
    # Formulaire pour enregistrer les détails d'un nouvel utilisateur.
    
    conditions = forms.CharField(widget=forms.Textarea(attrs={'readonly':'readonly', 'rows':'5'}))
    
    class Meta:
        model = UserDetails
        exclude = ("user",)
        widgets = {
            'birthdate': forms.DateInput(attrs={'class':'datepicker'}),
        }
        
    def __init__(self, *args, **kwargs):
        super(RegistrationDetailsForm, self).__init__(*args, **kwargs)

        # Charger la licence dans la langue préférée de l'utilisateur.
        this_dir = os.path.dirname(__file__)
        rel_path = "../../licenses/license_%s.txt" % get_language()
        abs_file_path = os.path.join(this_dir, rel_path)
        
        try:
            license = open(abs_file_path, 'r').read()
        except:
            license = _("Unable to load the license at this time.")
            
        self.fields['conditions'].initial = license
        
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            'birthdate', 'tel', 'city', 'country', 'region', 'address1', 'address2', 'zip', 'conditions', 'consent_cp'
        )
        
    def clean_consent_cp(self):
        """
        Vérifie que l'utilisateur a bel et bien accepté les conditions d'utilisation du site.
        """
        consent_cp = self.cleaned_data['consent_cp']
        
        if consent_cp == False: raise forms.ValidationError(_("I agree to the Terms of Use, EULA and Privacy Policy"))
        
        return consent_cp

class EditAccountForm(AbstractUserChangeForm):
    # Formulaire concret de modification d'un utilisateur.
        
    def __init__(self, *args, **kwargs):
        super(EditAccountForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
    
class EditAccountDetailsForm(forms.ModelForm):
    # Formulaire pour enregistrer les modifications des détails d'un utilisateur.
    
    class Meta:
        model = UserDetails
        exclude = ("user", "consent_cp")
        widgets = {
            'birthdate': forms.DateInput(attrs={'class':'datepicker'}),
        }
        
    def __init__(self, *args, **kwargs):
        super(EditAccountDetailsForm, self).__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.form_tag = False
        
        self.helper.layout = Layout(
            'birthdate', 'tel', 'city', 'country', 'region', 'address1', 'address2', 'zip',
        )

class ShippingAddressForm(forms.ModelForm):
    # Formulaire pour enregistrer une adresse de livraison.
    
    class Meta:
        model = UserAddress
        exclude = ("user", "default",)
        
    def __init__(self, *args, **kwargs):
        super(ShippingAddressForm, self).__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            'city', 'country', 'region', 'address1', 'address2', 'zip',
        )
        
    def save(self, commit=True):
        """
        Enregistre la nouvelle adresse en tant qu'adresse par défaut.
        """
        instance = super(ShippingAddressForm, self).save(commit=False)
        
        instance.default = True
        if commit:
            instance.save()
        return instance
        
class CreateRestaurateurForm(AbstractUserCreationForm):
    # Formulaire pour créer un nouveau restaurateur.
    
    restaurant = forms.ModelChoiceField(queryset=Restaurant.objects.all(), label=_("Restaurant"), required=False)
    
    def __init__(self, *args, **kwargs):
        super(CreateRestaurateurForm, self).__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'first_name', 'last_name', 'email', 'password1', 'password2', 'restaurant',
            Submit('save', _("Save"))
        )
        
class UpdateRestaurateurForm(AbstractUserChangeForm):
    # Formulaire pour enregistrer les modifications faites à un restaurateur.
    
    restaurant = forms.ModelChoiceField(queryset=Restaurant.objects.all(), label=_("Restaurant"), required=False)
    
    def __init__(self, *args, **kwargs):
        super(UpdateRestaurateurForm, self).__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'first_name', 'last_name', 'email', 'restaurant',
            Submit('save', _("Save")), Button('delete', _("Delete this restaurateur"), css_class='btn-danger'), 
        )
        

modules/restaurant/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.contrib import messages
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.forms import ModelForm
from django.forms.formsets import formset_factory
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit
from django.forms.models import BaseInlineFormSet, inlineformset_factory
from django.utils.encoding import smart_unicode
from django.utils.translation import ugettext_lazy as _

from extras.fields import COUNTRIES_LIST

from models import Meal, Menu, Restaurant

class UserFullnameChoiceField(forms.ModelChoiceField):
    # Champ de sélection des utilisateurs par leur nom complet.
    
    def label_from_instance(self, obj):
        return smart_unicode(obj.get_full_name())
        
class RestaurantFilterForm(forms.Form):
    city = forms.CharField(label=_("city"), required=False)
    region = forms.CharField(label=_("state/province"), required=True)
    country = forms.ChoiceField(label=_("country"), required=True, choices=COUNTRIES_LIST)
    
    def __init__(self, *args, **kwargs):
        super(RestaurantFilterForm, self).__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            'country', 'region', 'city', Submit('search', _("Search"), css_class="btn-success")
        )
        
class RestaurantEditFilterForm(forms.Form):
    city = forms.CharField(label=_("city"), required=False)
    region = forms.CharField(label=_("state/province"), required=False)
    country = forms.ChoiceField(label=_("country"), required=False, choices=COUNTRIES_LIST)
    
    def __init__(self, *args, **kwargs):
        super(RestaurantEditFilterForm, self).__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            'country', 'region', 'city', Submit('search', _("Search"))
        )
        
class RestaurantForm(ModelForm):
    restaurateur = UserFullnameChoiceField(queryset=User.objects.all())

    def __init__(self, *args, **kwargs):
        super(RestaurantForm, self).__init__(*args, **kwargs)
        self.fields['restaurateur'].queryset = User.objects.filter(groups__name='Restaurateur')
        self.helper = FormHelper()
        self.helper.form_tag = False
        
    class Meta:
        model = Restaurant
        fields = ['name', 'tel', 'country', 'region', 'city', 'address1', 'address2', 'zip', 'image', 'restaurateur']
        
class MenuForm(ModelForm):
    
    def __init__(self, *args, **kwargs):
        super(MenuForm, self).__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'name', 'restaurant', Submit('save', _("Save"))
        )
        
    class Meta:
        model = Menu
        fields = ['name', 'restaurant']
        
class MealForm(ModelForm):
    
    def __init__(self, *args, **kwargs):
        super(MealForm, self).__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'name', 'description', 'price', 'taxable', 'image', 'menu', Submit('save', _("Save"))
        )
        
    class Meta:
        model = Meal
        fields = ['name', 'description', 'price', 'taxable', 'image', 'menu', ]

templates/accounts/create_restaurateur.html
{% extends "accounts/dashboard.html" %}
{% load crispy_forms_tags i18n %}

{% block title %}{% trans "Creating a restaurateur" %}{% endblock %}

{% block content-pane %}
<div class="col-md-12">
    <h2 class="page-title">{% trans "Create a restaurateur" %}</h2>
	{% if messageType and message %}<div class="alert alert-{{messageType}}" role="alert">{{message}}</div>{% endif %}
	{% crispy form %}
</div>
{% endblock %}

templates/accounts/create_restaurator.html
{% extends "accounts/dashboard.html" %}
{% load crispy_forms_tags i18n %}

{% block title %}{% trans "Creating a restaurateur" %}{% endblock %}

{% block content-pane %}
<div class="col-md-12">
    <h2 class="page-title">{% trans "Create a restaurateur" %}</h2>
	{% if messageType and message %}<div class="alert alert-{{messageType}}" role="alert">{{message}}</div>{% endif %}
	{% crispy form %}
</div>
{% endblock %}

templates/accounts/delete_account.html
{% extends "base.html" %}
{% load crispy_forms_tags i18n %}

{% block title %}{% trans "Delete my account" %}{% endblock %}

{% block content %}
<div class="col-md-12">
	<form id="delete-form" method="post" action="">
		{% csrf_token %}
		{{form|crispy}}
        <p>{% trans "Are you sure you want to delete this account?" %}</p>
		<button type="submit" class="btn btn-primary">
			<span class="fa fa-check"></span> {% trans "Delete my account" %}
		</button>
	</form>
</div>
{% endblock %}

templates/accounts/header-login.html
<div id="header-login" class="col-md-3 col-xs-12">
	{% if request.user.is_authenticated %}
		<div class="text-right">
			<p class="no-marginBottom">Vous êtes connecté avec <strong>{{ request.user.username }}</strong></p>
			<a class="borderRight paddingRight5" href="{% url 'manage_account' %}"><span class="fa fa-cog"></span> Mon compte</a>
			<a class="paddingLeft5" href="{% url 'logout' %}?next={{request.path}}"><span class="fa fa-power-off"></span> Déconnexion</a>
		</div>
	{% else %}
		<div class="text-right">
			<a id="login-form-box-toogle-button" class="borderRight paddingRight10" href="#"><span class="fa fa-power-on"></span> S'identifier</a>
			<a class="paddingLeft10" href="{% url 'register' %}">Créer un compte</a>
		</div>
		
		<div id="login-form-box" class="no-element marginTop20 paddingBottom30">
			<form id="login-form" method="post" action="{% url 'login' %}?next={{request.path}}">
				{% csrf_token %}
				<div class="form-group">
					<input name="username" placeholder="Nom d'utilisateur *" class="form-control" type="text"/>
				</div>
				<div class="form-group">
					<input name="password" placeholder="Mot de passe *" class="form-control" type="password"/>
				</div>
				<button type="submit" class="btn btn-primary"><span class="fa fa-user"></span> S'identifier</button>
			</form>
		</div>
	{% endif %}
</div>

templates/accounts/header_login.html
{% load i18n %}
{% get_available_languages as LANGUAGES %}
<div id="header-login" class="col-md-5 col-xs-12">
{% if request.user.is_authenticated %}
	<div class="text-center">
		
		<div class="clearfix"></div>
		<ul class="nav navbar-nav navbar-right accountMenu">
			<li>
				<a class="paddingRight5" href="{% url 'accounts:manage_account' %}"><span class="fa fa-user"></span> {% trans "My account" %}</a>
			</li>
			<li>
				<a class="paddingLeft5" href="{% url 'accounts:logout' %}?next={{request.path}}"><span class="fa fa-power-off"></span> {% trans "Sign out" %}</a>
			</li>
			<li>
				<a href="#" id="languageSelection" data-toggle="dropdown" class="paddingLeft5">
					<span class="fa fa-language"></span>
					{% trans "Select language" %} 
					<span class="caret"></span>
				</a>
				<ul class="dropdown-menu" aria-labelledby="languageSelection">
					{% for lang, name in LANGUAGES %}
					<li><a href="{% url 'select_language' lang  %}">{{ name }}</a></li>
					{% endfor %}
				</ul>
			</li>
		</ul>
	</div>
{% else %}
	<div class="text-center">
		<ul class="nav navbar-nav navbar-right accountMenu">
			<li>
				<a class="show-login-form-modal paddingRight5" href="#"><span class="fa fa-lock"></span> {% trans "Sign in" %}</a>
			</li>
			<li>
				<a class="paddingLeft5" href="{% url 'accounts:register' %}"><span class="fa fa-user-plus"></span> {% trans "Inscription" %}</a>
			</li>
			<li>
				<a href="#" id="languageSelection" data-toggle="dropdown" class="paddingLeft5">
					<span class="fa fa-language"></span>
					{% trans "Select language" %} 
					<span class="caret"></span>
				</a>
				<ul class="dropdown-menu" aria-labelledby="languageSelection">
					{% for lang, name in LANGUAGES %}
					<li><a href="{% url 'select_language' lang  %}">{{ name }}</a></li>
					{% endfor %}
				</ul>
			</li>
		</ul>
	</div>
	
	<div class="modal fade" id="login-form-modal" tabindex="-1" role="dialog" aria-labelledby="login-form-modal-label">
		<form id="login-form" method="post" action="{% url 'accounts:login' %}?next={{request.path}}">
	 		<div class="modal-dialog" role="document">
	   			<div class="modal-content">
	     			<div class="modal-header">
	       				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	       				<h4 class="modal-title" id="login-form-modal-label">{% trans "Identification" %}</h4>
	     			</div>
	     			<div class="modal-body">
						{% csrf_token %}
						<div class="form-group">
							<input name="username" placeholder="{% trans "Email" %}" class="form-control" type="text"/>
						</div>
						<div class="form-group">
							<input name="password" placeholder="{% trans "Password" %}" class="form-control" type="password"/>
						</div>
	     			</div>
	      			<div class="modal-footer">
	        			<button type="button" class="btn btn-default" data-dismiss="modal"><span class="fa fa-times"></span> {% trans "Cancel" %}</button>
	        			<button type="submit" class="btn btn-success"><span class="fa fa-lock"></span> {% trans "Sign in" %}</button>
	      			</div>
	   			</div>
	 		</div>
 		</form>
	</div>
{% endif %}
</div>

templates/accounts/login.html
{% extends "base.html" %}
{% load crispy_forms_tags i18n %}

{% block title %}{% trans "Identification" %}{% endblock %}

{% block header-login %}{% endblock %}

{% block content %}
<div class="col-md-5">
	<form id="login-form" method="post" action="">
		<h2 class="page-title">{% trans "Identification" %}</h2>
		{% csrf_token %}
		{{loginForm|crispy}}
		
		<button type="submit" class="btn btn-primary pull-left" style="margin:0 20px 10px 0">
			<span class="fa fa-user"></span> {% trans "Sign in" %}
		</button>
		
		<div class="pull-left marginTop6">
			<a class="paddingLeft5" href="{% url 'accounts:register' %}">
				<span class="fa fa-user-plus"></span> <strong>{% trans "You don't have an account?" %}</strong>
			</a>
		</div>
		
	</form>
</div>
{% endblock %}

templates/accounts/manage_restaurateur.html
{% extends "accounts/dashboard.html" %}
{% load crispy_forms_tags i18n %}

{% block title %}{% trans "Update a restaurateur" %}{% endblock %}

{% block content-pane %}
<div class="col-md-12">
    <h2 class="page-title">{% trans "Update a restaurateur" %}</h2>
	{% if messageType and message %}<div class="alert alert-{{messageType}}" role="alert">{{message}}</div>{% endif %}
	{% crispy form %}
</div>
{% endblock %}

{% block page-scripts %}
<script type="text/javascript">
$('#button-id-delete').click(function() {
	window.location.href='{% url "accounts:restaurateurs_delete" object.pk %}';
});
</script>
{% endblock %}

templates/accounts/manage_restaurator.html
{% extends "accounts/dashboard.html" %}
{% load crispy_forms_tags i18n %}

{% block title %}{% trans "Update a restaurateur" %}{% endblock %}

{% block content-pane %}
<div class="col-md-12">
    <h2 class="page-title">{% trans "Update a restaurateur" %}</h2>
	{% if messageType and message %}<div class="alert alert-{{messageType}}" role="alert">{{message}}</div>{% endif %}
	{% crispy form %}
    
    
    <button type="button" id="delete-btn" class="btn btn-danger">
        <span class="fa fa-trash-o"></span> {% trans "Delete this restaurateur" %}
    </button>
</div>
{% endblock %}

{% block page-scripts %}
<script type="text/javascript">
    $('#delete-btn').click(function() {
            window.location.href='{% url "accounts:restaurators_delete" object.pk %}';
    });
</script>
{% endblock %}

templates/accounts/register.html
{% extends "base.html" %}
{% load crispy_forms_tags i18n %}

{% block title %}{% trans "Inscription" %}{% endblock %}

{% block content %}
<div class="col-md-12">
	<form id="register-form" method="post" action="">
		<h2 class="page-title">{% trans "Inscription" %}</h2>
		{% if user.id %}
		<div class="alert alert-block alert-success">
			<ul>
				<li>
					{% trans "Your customer account has been created, you can now sign in!" %}
				</li>
			</ul>
		</div>
		{% else %}
			{% csrf_token %}
			
			<div class="clearfix">
				{% crispy registerForm %}
			</div>
			
			<div class="clearfix">
				<h3 class="page-title">Information personnel</h3>
				{% crispy registerDetailsForm %}
			</div>
			<button type="submit" class="btn btn-success">
				<span class="fa fa-check"></span> {% trans "Register" %}
			</button>
		{% endif %}
	</form>
</div>
{% endblock %}

{% block head %}
<link href="{{ STATIC_URL }}bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css" rel="stylesheet"/>
{% endblock %}

{% block page-scripts %}
<script type="text/javascript" src="{{ STATIC_URL }}bootstrap/js/collapse.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}bootstrap/js/transition.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/moment.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js"></script>

<script type="text/javascript">
$(document).ready(function() {
    
	RegionSelector.init("#id_country", "#id_region");
    
	$('.datepicker').datetimepicker({
		format: "YYYY-MM-DD"
	});
    
    $("#page-content .form-group").addClass("col-md-6");
    
 
    
    $("#div_id_conditions").removeClass("col-md-6");
});
</script>
{% endblock %}

templates/accounts/restaurateur_list.html
{% extends "accounts/dashboard.html" %}
{% load i18n %}

{% block title %}{% trans "Creating a restaurateur" %}{% endblock %}

{% block content-pane %}
<div class="col-md-12">
	<h2 class="page-title">{% trans "Select a restaurateur to edit" %}</h2>
	
    <table class="table">
        <thead>
            <tr>
                <th>{% trans "Name" %}</th>
                <th>{% trans "Email address" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for r in restaurateurs %}
            <tr>
                <td><a href="{% url 'accounts:restaurateurs_manage' r.pk %}">{{ r.first_name }} {{ r.last_name }}</a></td>
                <td><a href="{% url 'accounts:restaurateurs_manage' r.pk %}">{{ r.email }}</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/accounts/restaurator_list.html
{% extends "accounts/dashboard.html" %}
{% load i18n %}

{% block title %}{% trans "Creating a restaurant - " %}{% endblock %}

{% block content-pane %}
<div class="col-md-12">
    <table class="table">
        <thead>
            <tr>
                <th>{% trans "Name" %}</th>
                <th>{% trans "Email address" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for r in restaurateurs %}
            <tr>
                <td><a href="{% url 'accounts:restaurators_manage' r.pk %}">{{ r.first_name }} {{ r.last_name }}</a></td>
                <td><a href="{% url 'accounts:restaurators_manage' r.pk %}">{{ r.email }}</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}