modules/restaurant/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from views import *

urlpatterns = patterns('',
    # Pour l'entrepreneur
    url(r'^create/$', RestaurantCreateView.as_view(), name="restaurant_create"),
    url(r'^(?P<pk>\d+)/update/$', RestaurantUpdateView.as_view(), name="restaurant_update"),
    url(r'^(?P<pk>\d+)/delete/$', RestaurantDeleteView.as_view(), name="restaurant_delete"),
    url(r'^list/$', RestaurantListView.as_view(), name="restaurant_list"),
    
    # Pour les restaurateurs
    url(r'^menus/create/$', MenuCreateView.as_view(), name="menu_create"),
    url(r'^menus/update/(?P<pk>\d+)$', MenuUpdateView.as_view(), name="menu_update"),
    url(r'^menus/list/$', MenuListView.as_view(), name="menu_list"),
    
    url(r'^meals/create/$', MealCreateView.as_view(), name="meal_create"),
    url(r'^meals/update/(?P<pk>\d+)$', MealUpdateView.as_view(), name="meal_update"),
    
    # Public
    url(r'^(?P<pk>\d+)/$', RestaurantDetailView.as_view(), name="restaurant_detail"),
    url(r'^$', RestaurantsView.as_view(), name="restaurants"),
)

urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.contrib import admin

import views

urlpatterns = patterns('',
	url(r'^$', views.HomeView.as_view(), name="home"),
	url(r'^admin/', include(admin.site.urls)), # Utile dans quelques rare cas
	url(r'^accounts/', include('accounts.urls', namespace="accounts")),
	url(r'^orders/', include('orders.urls', namespace="orders")),
    url(r'^restaurant/', include('restaurant.urls', namespace="restaurant")),
    url(r'^select_language/(?P<lang_code>\w+)/$', views.SelectLanguageView.as_view(), name="select_language"),
    url(r'^about/', views.TemplateView.as_view(template_name="about.html"), name="about"),
    url(r'^webservice/', include('webservice.urls', namespace="webservice")),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

modules/restaurants/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from django_countries.fields import CountryField
from django.utils.translation import ugettext_lazy as _

class Restaurant(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, verbose_name=_("restaurateur"))
    name = models.CharField(max_length=250, verbose_name=_("name"))
    tel = models.CharField(max_length=30, verbose_name=_("telephone"))
    city = models.CharField(max_length=250, verbose_name=_("city"))
    region = models.CharField(max_length=250, verbose_name=_("province/state/region"))
    country = CountryField(verbose_name=_("country"))
    address1 = models.CharField(max_length=250, verbose_name=_("address 1"))
    address2 = models.CharField(max_length=250, null=True, blank=True, verbose_name=_("address 2"))
    zip = models.CharField(max_length=10, verbose_name=_("zip code"))
    
    image = models.ImageField(upload_to='restaurants', verbose_name=_("image"), blank=True, null=True)
    
    admin_order_field = 'name'
    
    def __unicode__(self):
        return u'%s' % self.name
    
    class Meta:
        app_label = 'restaurants'
        db_table = 'restaurants_restaurant'
        verbose_name = 'Restaurant'
        verbose_name_plural = 'Restaurants'
        
class Meal(models.Model):
    restaurant = models.ForeignKey(Restaurant, verbose_name=_("restaurant"))
    name = models.CharField(max_length=250, verbose_name=_("name"))
    image = models.ImageField(upload_to='restaurants/meals', verbose_name=_("image"), blank=True, null=True)
    
    def __unicode__(self):
        return u'%s' % self.name
    
    class Meta:
        app_label = 'restaurants'
        db_table = 'restaurants_meal'
        verbose_name = 'Repas'
        verbose_name_plural = 'Repas'

class MealTag(models.Model):
    tag = models.CharField(max_length=250, verbose_name=_("tag"))
    meals = models.ManyToManyField(Meal, verbose_name=_("meals"))
    
    class Meta:
        app_label = 'restaurants'
        db_table = 'restaurants_mealtag'
        verbose_name = 'Tag de repas'
        verbose_name_plural = 'Tag de repas'
    

modules/restaurant/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.contrib import messages
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.forms import ModelForm
from django.forms.formsets import formset_factory
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit
from django.forms.models import BaseInlineFormSet, inlineformset_factory
from django.utils.encoding import smart_unicode
from django.utils.translation import ugettext_lazy as _

from extras.fields import COUNTRIES_LIST

from models import Meal, Menu, Restaurant

class UserFullnameChoiceField(forms.ModelChoiceField):
    # Champ de sélection des utilisateurs par leur nom complet.
    
    def label_from_instance(self, obj):
        return smart_unicode(obj.get_full_name())
        
class RestaurantFilterForm(forms.Form):
    city = forms.CharField(label=_("city"), required=False)
    region = forms.CharField(label=_("state/province"), required=True)
    country = forms.ChoiceField(label=_("country"), required=True, choices=COUNTRIES_LIST)
    
    def __init__(self, *args, **kwargs):
        super(RestaurantFilterForm, self).__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            'country', 'region', 'city', Submit('search', _("Search"), css_class="btn-success")
        )
        
class RestaurantEditFilterForm(forms.Form):
    city = forms.CharField(label=_("city"), required=False)
    region = forms.CharField(label=_("state/province"), required=False)
    country = forms.ChoiceField(label=_("country"), required=False, choices=COUNTRIES_LIST)
    
    def __init__(self, *args, **kwargs):
        super(RestaurantEditFilterForm, self).__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            'country', 'region', 'city', Submit('search', _("Search"))
        )
        
class RestaurantForm(ModelForm):
    restaurateur = UserFullnameChoiceField(queryset=User.objects.all())

    def __init__(self, *args, **kwargs):
        super(RestaurantForm, self).__init__(*args, **kwargs)
        self.fields['restaurateur'].queryset = User.objects.filter(groups__name='Restaurateur')
        self.helper = FormHelper()
        self.helper.form_tag = False
        
    class Meta:
        model = Restaurant
        fields = ['name', 'tel', 'country', 'region', 'city', 'address1', 'address2', 'zip', 'image', 'restaurateur']
        
class MenuForm(ModelForm):
    
    def __init__(self, *args, **kwargs):
        super(MenuForm, self).__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'name', 'restaurant', Submit('save', _("Save"))
        )
        
    class Meta:
        model = Menu
        fields = ['name', 'restaurant']
        
class MealForm(ModelForm):
    
    def __init__(self, *args, **kwargs):
        super(MealForm, self).__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'name', 'description', 'price', 'taxable', 'image', 'menu', Submit('save', _("Save"))
        )
        
    class Meta:
        model = Meal
        fields = ['name', 'description', 'price', 'taxable', 'image', 'menu', ]

modules/restaurant/views.py
# -*- coding: utf-8 -*-

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import Http404, HttpResponseForbidden, HttpResponseRedirect
from django.template.response import TemplateResponse
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext_lazy as _
from django.views.generic import DetailView, UpdateView
from django.views.generic.base import View
from django.views.generic.edit import CreateView, DeleteView
from django.views.generic.list import ListView
from django.shortcuts import get_object_or_404

try: from django.contrib.gis.geoip import GeoIP
except: GeoIP = None

from models import Meal, Menu, Restaurant
from forms import MealForm, MenuForm, RestaurantFilterForm, RestaurantForm, RestaurantEditFilterForm

from accounts.mixins import AllowedGroupsMixin
from accounts.models import UserAddress

#
# Public Views
#
class RestaurantsView(View):
    template_name = 'restaurant/list.html'
    RESTAURANTS_BY_PAGE = 5
    
    def get(self, request, *args, **kwargs):
        if request.user_details and not request.user_details.is_a_client():
            return HttpResponseRedirect(reverse('accounts:dashboard'))
        
        pageNum = request.GET.get('p', 1)
        city = request.GET.get('city')
        region = request.GET.get('region')
        country = request.GET.get('country')
        
        #
        # By default takes user's default delivery address
        #
        if request.user.is_authenticated():
            deliveryAddresses = UserAddress.objects.filter(user=request.user).order_by('-default')
            
            if (not city or not region or not country) and deliveryAddresses:
                city = deliveryAddresses[0].city
                region = deliveryAddresses[0].region
                country = deliveryAddresses[0].country
        
        #
        # Otherwise takes the user_details location
        #
        if (not city or not region or not country) and \
            request.user.is_authenticated() and request.user_details:
            city = request.user_details.city
            region = request.user_details.region
            country = request.user_details.country
        
        #
        # GeoIp checkup to get the current city
        #
        elif (not city or not region or not country) and GeoIP:
            geoip = GeoIP()
            
            ip = request.META.get('REMOTE_ADDR')
            cityData = geoip.city(ip)
            
            if cityData:
                city = cityData.get('city')
                region = cityData.get('region')
                country = cityData.get('country_code')
        
        if (city and region and country) or (not city and region and country):
            filterForm = RestaurantFilterForm(data={'city':city,
                                                    'region':region,
                                                    'country':country})
        else: filterForm = RestaurantFilterForm()
        
        if city and region and country:
            objects = Restaurant.objects.filter(city=city, region=region, country=country).order_by('name')
        elif not city and region and country:
            objects = Restaurant.objects.filter(region=region, country=country).order_by('name')
        else:
            objects = Restaurant.objects.all().order_by('name')
        
        paginator = Paginator(objects, self.RESTAURANTS_BY_PAGE)
        
        try:
            page = paginator.page(pageNum)
        except PageNotAnInteger:
            page = paginator.page(1)
        except EmptyPage:
            page = paginator.page(paginator.num_pages)
        
        return TemplateResponse(request, self.template_name, {'page':page,
                                                              'paginator':paginator,
                                                              'city':city,
                                                              'region':region,
                                                              'country':country,
                                                              'filterForm':filterForm})

class RestaurantDetailView(DetailView):
    model = Restaurant
    template_name = 'restaurant/detail.html'
    context_object_name = 'restaurant'

#
# Entrepreneur Views
#
class RestaurantCreateView(AllowedGroupsMixin, CreateView):
    allowed_groups = ['Entrepreneur',]
    form_class = RestaurantForm
    template_name = 'restaurant/create.html'
    success_url = reverse_lazy('restaurant:restaurant_create')
    
    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        
        if (form.is_valid()):
            name = form.cleaned_data.get("name")
            restaurateur = form.cleaned_data.get("restaurateur")
            
            if restaurateur:
                messages.success(self.request, _("'%s' has been successfully created" % name))
            else:
                messages.warning(self.request, _("'%s' has been successfully created but doesn't have an assigned restaurateur" % name))
                
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
            
class RestaurantUpdateView(AllowedGroupsMixin, UpdateView):
    allowed_groups = ['Entrepreneur', ]
    form_class = RestaurantForm
    model = Restaurant
    success_url = reverse_lazy('restaurant:restaurant_list')
    template_name = 'restaurant/update.html'
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        
        if (form.is_valid()):
            name = form.cleaned_data.get("name")
            restaurateur = form.cleaned_data.get("restaurateur")
            
            if restaurateur:
                messages.success(self.request, _("'%s' has been successfully updated" % name))
            else:
                messages.warning(self.request, _("'%s' has been successfully updated but doesn't have an assigned restaurateur" % name))
                
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
    
class RestaurantDeleteView(AllowedGroupsMixin, DeleteView):
    allowed_groups = ['Entrepreneur', ]
    model = Restaurant
    success_url = reverse_lazy('restaurant:restaurant_list')
    template_name = 'restaurant/delete.html'

class RestaurantListView(AllowedGroupsMixin, ListView):
    allowed_groups = ['Entrepreneur', ]
    context_object_name = 'restaurants'
    model = Restaurant
    template_name = 'restaurant/edit_list.html'
    
    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        
        city = self.request.GET.get('city')
        region = self.request.GET.get('region')
        country = self.request.GET.get('country')
        
        filterForm = RestaurantEditFilterForm(data={'city':city, 'region':region, 'country':country})
            
        return self.render_to_response(
            self.get_context_data(filterForm=filterForm,))
    
    def get_queryset(self):
        city = self.request.GET.get('city')
        region = self.request.GET.get('region')
        country = self.request.GET.get('country')
        
        if not city and not region and not country:
            queryset = Restaurant.objects.all().order_by('name')
        else:
            if city and region and country:
                queryset = Restaurant.objects.filter(city=city, region=region, country=country).order_by('name')
            elif region and country:
                queryset = Restaurant.objects.filter(region=region, country=country).order_by('name')
            else:
                messages.error(self.request, _("You can search without a city, but the other fields are required."))
                queryset = Restaurant.objects.none()
            
        return queryset
    
#
# Restaurateur Views
#
class MenuCreateView(CreateView):
    template_name = 'restaurant/menus/create.html'
    form_class = MenuForm
    model = Menu
    success_url = reverse_lazy('restaurant:menu_list')
    
    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        
        if (form.is_valid()):
            name = form.cleaned_data.get("name")
            messages.success(self.request, _("'%s' has been successfully created" % name))
                
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
    
class MenuListView(AllowedGroupsMixin, ListView):
    allowed_groups = ['Restaurateur', ]
    model = Menu
    template_name = 'restaurant/menus/list.html'
    
    def get_context_data(self, **kwargs):
        context = super(MenuListView, self).get_context_data(**kwargs)
        context['restaurants'] = Restaurant.objects.filter(restaurateur=self.request.user)
        return context

class MenuUpdateView(UpdateView):
    template_name = 'restaurant/menus/update.html'
    form_class = MenuForm
    model = Menu
    success_url = reverse_lazy('restaurant:menu_list')
    
    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        
        if (form.is_valid()):
            name = form.cleaned_data.get("name")
            messages.success(self.request, _("'%s' has been successfully updated" % name))
                
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
    

templates/restaurant/menus/create.html
{% extends "accounts/dashboard.html" %}
{% load crispy_forms_tags i18n %}

{% block title %}{% trans "Create a menu" %}{% endblock %}

{% block content-pane %}
<div class="col-md-12">
    <form method="post" id="mForm" action="{% url 'restaurant:menu_create' %}"> {% csrf_token %}
        <h2 class="page-title">{% trans "New menu" %}</h2>

        {% crispy form %}
    </form>
</div>
{% endblock %}

templates/restaurant/menus/list.html
{% extends "accounts/dashboard.html" %}
{% load i18n %}

{% block title %}{% trans "Edit my menus" %}{% endblock %}

{% block content-pane %}
<div class="col-md-12">
    <h2>{% trans "Select a menu or a meal to edit" %}</h2>
    
    {% for r in restaurants %}
    <div class="panel panel-default">
        <div class="panel-heading">{{ r.name }} - {{ r.address1 }}</div>
            <div class="panel-body">
                <ul>
                    {% for m in r.menus %}
                        <li><a href="{% url 'restaurant:menu_update' m.pk %}">{{ m.name }}</a>
                            <ul>
                                {% for p in m.meals %}
                                    <li><a href="{% url 'restaurant:meal_update' p.pk %}">{{ p.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                    {% endfor %}
                        <li><a href="{% url 'restaurant:menu_create' %}">{% trans "Add a new menu" %}</a></li>
                        <li><a href="{% url 'restaurant:meal_create' %}">{% trans "Add a new meal" %}</a></li>
                </ul>
            </div>
    </div>
    {% empty %}
        <p>{% trans "You don't have any restaurant. You need to own at least one restaurant to create a menu." %}</p>
    {% endfor %}
</div>
{% endblock %}

templates/restaurant/menus/meal_create.html
{% extends "accounts/dashboard.html" %}
{% load crispy_forms_tags i18n %}

{% block title %}{% trans "Create a meal" %}{% endblock %}

{% block content-pane %}
<div class="col-md-12">
    <form method="post" id="mForm" action="{% url 'restaurant:meal_create' %}"> {% csrf_token %}
        <h2 class="page-title">{% trans "New meal" %}</h2>

        {% crispy form %}
    </form>
</div>
{% endblock %}

templates/restaurant/menus/meal_update.html
{% extends "accounts/dashboard.html" %}
{% load crispy_forms_tags i18n %}

{% block title %}{% trans "Edit a meal" %}{% endblock %}

{% block content-pane %}
<div class="col-md-12">
    <form method="post" id="mForm" action="{% url 'restaurant:meal_update' object.pk %}"> {% csrf_token %}
        <h2 class="page-title">{{ object.name }}</h2>

        {% crispy form %}
    </form>
</div>
{% endblock %}

templates/restaurant/menus/update.html
{% extends "accounts/dashboard.html" %}
{% load crispy_forms_tags i18n %}

{% block title %}{% trans "Edit a menu" %}{% endblock %}

{% block content-pane %}
<div class="col-md-12">
    <form method="post" id="mForm" action="{% url 'restaurant:menu_update' object.pk %}"> {% csrf_token %}
        <h2 class="page-title">{{ object.name }}</h2>
        
        <div class="panel panel-default">
            <div class="panel-heading">{% trans "Menu information" %}</div>
            <div class="panel-body">
                {% crispy form %}
        
                <button type="submit"class="btn btn-primary">
                    <span class="fa fa-check"></span> {% trans "Save" %}
                </button>
                
                <button type="button"class="btn btn-default" id="ajouterPlat">{% trans "Add a meal" %}</button>
            </div>
        </div>
        
        {{ meal_formset.management_form }}
            {% for form in meal_formset %}
            <div id="premierFormset">
                <div class="panel panel-default">
                    <div class="panel-heading">{% trans "New Meal" %}</div>
                    <div class="panel-body">
                        {% crispy form %}
                    </div>
                </div>
            </div>
            {% endfor %}
    </form>
</div>
{% endblock %}

{% block page-scripts %}
<script type="text/javascript">
$(document).ready(function() {
    $('#ajouterPlat').click(function() {
        var form_idx = $('#id_meal_set-TOTAL_FORMS').val();
        var $fs = $('#premierFormset').clone();
        
        $fs.find( "*" ).each(function(i,elem){
            if(typeof $(elem).attr("id") !== "undefined") {
                var oldId = $(elem).attr("id");
                var newId = oldId.replace(form_idx-1, form_idx);
                $(elem).attr("id", newId);
            }
        });
        
        $fs.find('.has-error').removeClass('has-error');
        $fs.find('input[type=text], input[type=number]').attr('value', '');
        
        $('#mForm').append($fs.html());
        $('#id_meal_set-TOTAL_FORMS').val(parseInt(form_idx) + 1);
    });
});
</script>
{% endblock %}