modules/orders/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
import views

urlpatterns = patterns('',
    url(r'^create/$', views.OrderCreatorView.as_view(), name="create"),
    url(r'^view/(?P<id>.+)/$', views.OrderDetailView.as_view(), name="detail"),
)

modules/restaurant/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from views import *

urlpatterns = patterns('',
    # Pour l'entrepreneur
    url(r'^create/$', RestaurantCreateView.as_view(), name="restaurant_create"),
    url(r'^(?P<pk>\d+)/update/$', RestaurantUpdateView.as_view(), name="restaurant_update"),
    url(r'^(?P<pk>\d+)/delete/$', RestaurantDeleteView.as_view(), name="restaurant_delete"),
    url(r'^list/$', RestaurantListView.as_view(), name="restaurant_list"),
    
    # Pour les restaurateurs
    url(r'^menus/create/$', MenuCreateView.as_view(), name="menu_create"),
    url(r'^menus/update/(?P<pk>\d+)$', MenuUpdateView.as_view(), name="menu_update"),
    url(r'^menus/list/$', MenuListView.as_view(), name="menu_list"),
    
    url(r'^meals/create/$', MealCreateView.as_view(), name="meal_create"),
    url(r'^meals/update/(?P<pk>\d+)$', MealUpdateView.as_view(), name="meal_update"),
    
    # Public
    url(r'^(?P<pk>\d+)/$', RestaurantDetailView.as_view(), name="restaurant_detail"),
    url(r'^$', RestaurantsView.as_view(), name="restaurants"),
)

urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.contrib import admin

import views

urlpatterns = patterns('',
	url(r'^$', views.HomeView.as_view(), name="home"),
	url(r'^admin/', include(admin.site.urls)), # Utile dans quelques rare cas
	url(r'^accounts/', include('accounts.urls', namespace="accounts")),
	url(r'^orders/', include('orders.urls', namespace="orders")),
    url(r'^restaurant/', include('restaurant.urls', namespace="restaurant")),
    url(r'^select_language/(?P<lang_code>\w+)/$', views.SelectLanguageView.as_view(), name="select_language"),
    url(r'^about/', views.TemplateView.as_view(template_name="about.html"), name="about"),
    url(r'^webservice/', include('webservice.urls', namespace="webservice")),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

modules/restaurant/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from django_countries.fields import CountryField
from django.utils.translation import ugettext_lazy as _

from extras.fields import CurrencyField

class Restaurant(models.Model):
    # Classe qui représente un restaurant.
    
    restaurateur = models.ForeignKey(User, null=True, blank=True, verbose_name=_("restaurateur"))
    name = models.CharField(max_length=250, verbose_name=_("name"))
    tel = models.CharField(max_length=30, verbose_name=_("telephone"))
    city = models.CharField(max_length=250, verbose_name=_("city"))
    region = models.CharField(max_length=250, verbose_name=_("province/state/region"))
    country = CountryField(verbose_name=_("country"))
    address1 = models.CharField(max_length=250, verbose_name=_("address 1"))
    address2 = models.CharField(max_length=250, null=True, blank=True, verbose_name=_("address 2"))
    zip = models.CharField(max_length=10, verbose_name=_("zip code"))
    image = models.ImageField(upload_to='restaurant/restaurants', blank=True, null=True, verbose_name=_("image"))
    
    def __unicode__(self):
        return self.name
        
    def get_address(self):
        return _("%(address1)s %(address2)s, %(city)s, %(region)s (%(country)s) %(zip)s") % {
            'address1':address1,
            'address2':address2,
            'city':city,
            'region':region,
            'country':country,
            'zip':zip,
        }
    
    @property
    def menus(self):
        return Menu.objects.filter(restaurant=self)
    
    class Meta:
         app_label = 'restaurant'
        
class Menu(models.Model):
    # Classe qui représente le menu d'un restaurant.
    
    restaurant = models.ForeignKey(Restaurant)
    name = models.CharField(max_length=250, verbose_name=_("name"))
    
    def __unicode__(self):
        return self.name
    
    @property
    def meals(self):
        return Meal.objects.filter(menu=self)
    
    class Meta:
         app_label = 'restaurant'
    
class Meal(models.Model):
    # Classe qui représente un plat qui se retrouve sur un menu.
    
    menu = models.ForeignKey(Menu)
    name = models.CharField(max_length=250, verbose_name=_("name"))
    description = models.CharField(max_length=250, blank=True, null=True, verbose_name=_("description"))
    price = CurrencyField(max_digits=10, decimal_places=2, verbose_name=_("price"))
    taxable = models.BooleanField(verbose_name=_("taxable"), default=True)
    image = models.ImageField(upload_to='restaurant/restaurants', blank=True, null=True, verbose_name=_("image"))
    
    def __unicode__(self):
        return self.name
    
    class Meta:
         app_label = 'restaurant'
    

modules/restaurants/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from django_countries.fields import CountryField
from django.utils.translation import ugettext_lazy as _

class Restaurant(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, verbose_name=_("restaurateur"))
    name = models.CharField(max_length=250, verbose_name=_("name"))
    tel = models.CharField(max_length=30, verbose_name=_("telephone"))
    city = models.CharField(max_length=250, verbose_name=_("city"))
    region = models.CharField(max_length=250, verbose_name=_("province/state/region"))
    country = CountryField(verbose_name=_("country"))
    address1 = models.CharField(max_length=250, verbose_name=_("address 1"))
    address2 = models.CharField(max_length=250, null=True, blank=True, verbose_name=_("address 2"))
    zip = models.CharField(max_length=10, verbose_name=_("zip code"))
    
    image = models.ImageField(upload_to='restaurants', verbose_name=_("image"), blank=True, null=True)
    
    admin_order_field = 'name'
    
    def __unicode__(self):
        return u'%s' % self.name
    
    class Meta:
        app_label = 'restaurants'
        db_table = 'restaurants_restaurant'
        verbose_name = 'Restaurant'
        verbose_name_plural = 'Restaurants'
        
class Meal(models.Model):
    restaurant = models.ForeignKey(Restaurant, verbose_name=_("restaurant"))
    name = models.CharField(max_length=250, verbose_name=_("name"))
    image = models.ImageField(upload_to='restaurants/meals', verbose_name=_("image"), blank=True, null=True)
    
    def __unicode__(self):
        return u'%s' % self.name
    
    class Meta:
        app_label = 'restaurants'
        db_table = 'restaurants_meal'
        verbose_name = 'Repas'
        verbose_name_plural = 'Repas'

class MealTag(models.Model):
    tag = models.CharField(max_length=250, verbose_name=_("tag"))
    meals = models.ManyToManyField(Meal, verbose_name=_("meals"))
    
    class Meta:
        app_label = 'restaurants'
        db_table = 'restaurants_mealtag'
        verbose_name = 'Tag de repas'
        verbose_name_plural = 'Tag de repas'
    

modules/restaurant/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.contrib import messages
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.forms import ModelForm
from django.forms.formsets import formset_factory
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit
from django.forms.models import BaseInlineFormSet, inlineformset_factory
from django.utils.encoding import smart_unicode
from django.utils.translation import ugettext_lazy as _

from extras.fields import COUNTRIES_LIST

from models import Meal, Menu, Restaurant

class UserFullnameChoiceField(forms.ModelChoiceField):
    # Champ de sélection des utilisateurs par leur nom complet.
    
    def label_from_instance(self, obj):
        return smart_unicode(obj.get_full_name())
        
class RestaurantFilterForm(forms.Form):
    city = forms.CharField(label=_("city"), required=False)
    region = forms.CharField(label=_("state/province"), required=True)
    country = forms.ChoiceField(label=_("country"), required=True, choices=COUNTRIES_LIST)
    
    def __init__(self, *args, **kwargs):
        super(RestaurantFilterForm, self).__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            'country', 'region', 'city', Submit('search', _("Search"), css_class="btn-success")
        )
        
class RestaurantEditFilterForm(forms.Form):
    city = forms.CharField(label=_("city"), required=False)
    region = forms.CharField(label=_("state/province"), required=False)
    country = forms.ChoiceField(label=_("country"), required=False, choices=COUNTRIES_LIST)
    
    def __init__(self, *args, **kwargs):
        super(RestaurantEditFilterForm, self).__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            'country', 'region', 'city', Submit('search', _("Search"))
        )
        
class RestaurantForm(ModelForm):
    restaurateur = UserFullnameChoiceField(queryset=User.objects.all())

    def __init__(self, *args, **kwargs):
        super(RestaurantForm, self).__init__(*args, **kwargs)
        self.fields['restaurateur'].queryset = User.objects.filter(groups__name='Restaurateur')
        self.helper = FormHelper()
        self.helper.form_tag = False
        
    class Meta:
        model = Restaurant
        fields = ['name', 'tel', 'country', 'region', 'city', 'address1', 'address2', 'zip', 'image', 'restaurateur']
        
class MenuForm(ModelForm):
    
    def __init__(self, *args, **kwargs):
        super(MenuForm, self).__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'name', 'restaurant', Submit('save', _("Save"))
        )
        
    class Meta:
        model = Menu
        fields = ['name', 'restaurant']
        
class MealForm(ModelForm):
    
    def __init__(self, *args, **kwargs):
        super(MealForm, self).__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'name', 'description', 'price', 'taxable', 'image', 'menu', Submit('save', _("Save"))
        )
        
    class Meta:
        model = Meal
        fields = ['name', 'description', 'price', 'taxable', 'image', 'menu', ]

templates/restaurant/create.html
{% extends "accounts/dashboard.html" %}
{% load crispy_forms_tags i18n %}

{% block title %}{% trans "Create a restaurant" %}{% endblock %}

{% block content-pane %}
<div class="col-md-12">
    <form id="new-restaurant-form" method="post" enctype="multipart/form-data" action="{% url 'restaurant:restaurant_create' %}" >
        <h2 class="page-title">{% trans "New restaurant" %}</h2>
        {% csrf_token %}
        {% crispy form %}
        <button type="submit" id="form-submit-btn" class="btn btn-primary">
            <span class="fa fa-check"></span> {% trans "Save" %}
        </button>
    </form>
</div>
{% endblock %}

{% block page-scripts %}
<script type="text/javascript">
$(document).ready(function() {
	RegionSelector.init("#new-restaurant-form #id_country", "#new-restaurant-form #id_region");
});
</script>
{% endblock %}

templates/restaurant/delete.html
{% extends "accounts/dashboard.html" %}
{% load i18n %}

{% block title %}{% trans "Delete a restaurant" %}{% endblock %}

{% block content-pane %}
<div class="col-md-12">
    <h2 class="page-title">{% blocktrans with object.name as name %}Delete {{ name }} ?{% endblocktrans %}</h2>
        
    <form method="post" action="{% url 'restaurant:restaurant_delete' object.pk %}">{% csrf_token %}
        <button type="submit" class="btn btn-primary">
            <span class="fa fa-trash-o"></span> {% trans "Click this button to confirm your choice" %}
        </button>
    </form>
</div>
{% endblock %}

templates/restaurant/detail.html
{% extends "base.html" %}
{% load thumbnail i18n %}

{% block title %}{{ restaurant.name }} - {% trans "Restaurants" %}{% endblock %}

{% block content %}
<div id="restaurant" class="{% if not request.user_details or request.user_details.is_a_client %}col-md-8{% else %}col-md-12{% endif %}">
	<div id="restaurant-details" class="clearfix">
		<h2 class="page-title">{{ restaurant.name }}</h2>
		
		{% if restaurant.image %}
			<div class="col-md-5">
				{% thumbnail restaurant.image 400x300 crop as thumb %}
		        <img class="image" src="{{thumb.url}}"/>
	        </div>
		{% endif %}
		
		<div id="map-canvas" {% if restaurant.image %}class="col-md-7"{% else %}class="col-md-12"{% endif %}></div>
	</div>
	
	{% if restaurant.menus %}
	<div id="restaurant-menu" class="panel-group" role="tablist" aria-multiselectable="true">
		<div class="panel panel-default">
			{% for menu in restaurant.menus %}
	    	<div class="panel-heading" role="tab" id="heading-menu-{{menu.id}}">
	      		<h4 class="panel-title">
	        		<a data-toggle="collapse" data-parent="#restaurant-menu" href="#menu-{{menu.id}}" aria-expanded="true" aria-controls="collapseOne">
	          			<span class="fa fa-user"> </span> {{ menu }}
	        		</a>
	      		</h4>
	    	</div>
	    	
	    	<div id="menu-{{menu.id}}" class="panel-collapse {% if forloop.counter == 1 %}in{% else %}collapse{% endif %}" role="tabpanel" aria-labelledby="heading-menu-{{menu.id}}">
	      		<div class="panel-body clearfix">
	      		{% for meal in menu.meals %}
	      			<div class="meal clearfix">
	      				<div class="col-md-3">
							{% if meal.image %}
								{% thumbnail meal.image 200x150 crop as thumb %}
		        				<img class="image" src="{{thumb.url}}" />
					        {% else %}
					        	<img class="image" src="{{ STATIC_URL }}img/placeholder-200x150.png" style="width:100%; height:auto;"/>
							{% endif %}
	      				</div>
	      				
	      				<div class="col-md-6">
		      				<h5>{{ meal }}</h5>
		      				<p class="description">{{meal.description}}</p>
		      				<p class="price"><strong>{{meal.price}}$</strong></p>
	      				</div>
	      				
	      				<div class="col-md-3">
		      				{% if not request.user_details or request.user_details.is_a_client %}
			      				<form id="meal-form-{{meal.id}}" class="well meal-form form-inline" onsubmit="return false">
			      					<div id="div_id_qte-{{meal.id}}" class="clearfix">
										<label class="control-label requiredField font22 pull-left" for="id_qte-{{meal.id}}">
											{% trans "Qte" %}
											<span class="asteriskField">* </span>
										</label>
										
										<div class="controls pull-left">
											<input id="id_qte-{{meal.id}}" class="textinput textInput form-control" name="qte" value="1">
										</div>
									</div>
									
									<input onclick="addMeal({{meal.id}})" id="add-meal-{{meal.id}}" class="btn btn-success" type="button" value="{% trans "Add to order" %}" name="add">
			      				</form>
		      				{% endif %}
	      				</div>
	      			</div>
	      		{% endfor %}
	      		</div>
	      	</div>
			{% endfor %}
		</div>
	</div>
	{% endif %}
</div>
{% if not request.user_details or request.user_details.is_a_client %}
<div id="my-order" class="col-md-4">
	<h3>{% trans "My order" %}</h3>
	
	<table class="table table-striped">
		<thead>
			<tr>
				<th>{% trans "Item" %}</th>
				<th class="text-right">{% trans "Qte" %}</th>
				<th style="width:75px" class="text-right">{% trans "Price" %}</th>
			</tr>
		</thead>
		<tbody>
			<tr id="emptyOrder">
				<td colspan="3" class="text-center">- {% trans "None" %} -</td>
			</tr>
			{% for menu in restaurant.menus %}{% for meal in menu.meals %}
			<tr id="order-meal-{{meal.id}}" class="hidden">
				<td>
					<a onclick="deleteMeal({{meal.id}})" class="btn btn-default btn-xs"><span class="fa fa-times"></span></a>
					{{ meal }}
				</td>
				<td id="order-meal-qte-{{meal.id}}" class="text-right"></td>
				<td class="text-right">{{meal.price}}$</td>
			</tr>
			{% endfor %}{% endfor %}
			<tr>
				<td colspan="2" class="text-right">{% trans "Subtotal" %}</td>
				<td id="subtotal" class="text-right">0.00$</td>
			</tr>
		</tbody>
	</table>
	
	<div class="text-right">
		<button id="create-order-button" class="btn btn-danger" disabled="disabled">{% trans "Order now!" %}</button>
	</div>
</div>
{% endif %}
{% endblock %}

{% block page-scripts %}
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?language={{ request.LANGUAGE_CODE }}&key=AIzaSyCWVV4JsXtPPqY6ngQB8G3MVHf6S3ylFQw"></script>
<script type="text/javascript">
var map;

// Client only {% if not request.user_details or request.user_details.is_a_client %}
var meals = { //{% for menu in restaurant.menus %}{% for meal in menu.meals %}
	'{{meal.id}}': {
		name: '{{meal|addslashes}}',
		price: '{{meal.price}}',
		qte: 0
	}{% if not forloop.last or not forloop.parentloop.last %},{% endif %}{% endfor %}{% endfor %}
};

function refreshMyOrder() {
	var subtotal = 0;
	
	for(var mealId in meals) {
		if(meals[mealId].qte>0) {
			subtotal += meals[mealId].qte * parseFloat(meals[mealId].price);
			
			$("#order-meal-qte-"+mealId).html(meals[mealId].qte);
			$("#order-meal-"+mealId).removeClass('hidden');
		} else {
			$("#order-meal-"+mealId).addClass('hidden');
		}
	}
	
	$("#subtotal").html(Utilities.truncateDecimals(subtotal, 2)+"$");
	
	if(subtotal==0) {
		$("#emptyOrder").removeClass('hidden');
		$("#create-order-button").attr("disabled", true);
	} else {
		$("#emptyOrder").addClass('hidden');
		$("#create-order-button").attr("disabled", false);
	}
}

function addMeal(id) {
	var qte = $("#id_qte-"+id).val();
	
	if(Utilities.isInt(qte)) {
		meals[id].qte = meals[id].qte + parseInt(qte);
		refreshMyOrder();
	}
	
	$("#id_qte-"+id).val(1);
}

function deleteMeal(id) {
	meals[id].qte=0;
	refreshMyOrder();
}

function createOrder() {
	var querys = [];
	
	for(var mealId in meals) {
		if(meals[mealId].qte>0) {
			querys.push(mealId+'='+meals[mealId].qte);
		}
	}
	
	window.location.href = "{% url 'orders:create' %}?" + querys.join('&');
}
// END{% endif %}

$(document).ready(function () {
	// Client only {% if not request.user_details or request.user_details.is_a_client %}
	refreshMyOrder();
	$("#create-order-button").click(createOrder);
	// END{% endif %}
	
	var jqxhr = $.get("https://maps.googleapis.com/maps/api/geocode/json?address={{ restaurant.zip|addslashes }}&key=AIzaSyCWVV4JsXtPPqY6ngQB8G3MVHf6S3ylFQw", function(data) {
		if(data.results.length>0) {
			//{% if restaurant.image %}
			$('#map-canvas').height($('#restaurant-details .image').height()); //{% endif %}
			
			var lat = data.results[0].geometry.location.lat;
			var lng = data.results[0].geometry.location.lng;
			
			var position = new google.maps.LatLng(lat, lng);
			
			var mapOptions = {
				center: position,
		      	zoom: 16,
		      	mapTypeId: google.maps.MapTypeId.HYBRID
		    };
			
			map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
		
		    var marker = new google.maps.Marker({
		        position: position,
		        map: map,
		        title: '{{ restaurant.name|addslashes }}'
		    });
		    
		    var infowindow = new google.maps.InfoWindow({
		        content: '<div id="content"><h1 id="firstHeading" class="firstHeading">{{ restaurant.name|addslashes }}</h1>' +
		        	'<div id="bodyContent"><p class="adr">{{ restaurant.address1|addslashes }}, {% if restaurant.address2 %}{{ restaurant.address2|addslashes }}, {% endif %}' + 
		        	'{{ restaurant.city|addslashes }}, {{ restaurant.region|addslashes }}, {{ restaurant.country|addslashes }}, {{ restaurant.zip|addslashes }}</p></div></div>'
		    });
		    
		    google.maps.event.addListener(marker, 'click', function() {
		    	infowindow.open(map, marker);
		    });
		} else {
			console.error('No locations found for zip code: {{ restaurant.zip|addslashes }}')
			$('#map-canvas').remove();
		}
	});
});
</script>
{% endblock %}

templates/restaurant/edit_list.html
{% extends "accounts/dashboard.html" %}
{% load crispy_forms_tags i18n %}

{% block title %}{% trans "Edit a restaurant" %}{% endblock %}

{% block content-pane %}
<div class="col-md-12">
    <h2 class="page-title">{% trans "Select a restaurant to edit" %}</h2>
    
    <div class="row" id="filterRow">
        <div class="col-md-12">
            <form id="filterForm" class="form-inline">
                {% crispy filterForm %}
            </form>
        </div>
    </div>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>{% trans "Name" %}</th>
                <th>{% trans "Address" %}</th>
                <th>{% trans "City" %}</th>
                <th>{% trans "Region" %}</th>
                <th>{% trans "Country" %}</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for r in restaurants %}
            <tr>
                <td><a href="{% url 'restaurant:restaurant_detail' r.pk %}">{{ r.name }}</a></td>
                <td>{{ r.address1 }} {{ r.address2 }}</td>
                <td>{{ r.city }}</td>
                <td>{{ r.region }}</td>
                <td>{{ r.country }}</td>
                <th><a href="{% url 'restaurant:restaurant_update' r.pk %}">{% trans "Update" %}</a></th>
                <th><a href="{% url 'restaurant:restaurant_delete' r.pk %}">{% trans "Delete" %}</a></th>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block page-scripts %}
<script type="text/javascript">
$(document).ready(function() {
	RegionSelector.init("#filterForm #id_country", "#filterForm #id_region")
});
</script>
{% endblock %}

templates/restaurant/list.html
{% extends "base.html" %}
{% load thumbnail crispy_forms_tags i18n %}

{% block title %}{% trans "Restaurants" %}{% endblock %}

{% block content %}
<div class="col-md-12">
    <div class="row" id="filterRow">
        <div class="col-md-12">
            <form id="filterForm" class="form-inline">
                {% crispy filterForm %}
            </form>
        </div>
    </div>
	
    <div class="row">
        <div class="col-md-12">
            <div id="restaurants" class="clearfix">
                {% for r in page %}
	                <div class="restaurant col-md-3">
	                    {% if r.image %}
	                    	{% thumbnail r.image 320x240 crop as thumb %}
	                    	<img src="{{thumb.url}}" class="image"/>
	                    {% endif %}
	                    
	                    <div class="boxTexte">
		                    <h2 class="text-center">{{ r.name }}</h2>
		                    
		                    <p class="adr text-center">{{ r.address1 }}</p> 
		                    
		                    {% if r.address2 %}
		                    	<p class="adr text-center">{{ r.address2 }}</p>
		                    {% endif %}
		                    
		                    <p class="adr text-center">{{ r.city }}, {{ r.region }}, {{ r.country }}, {{ r.zip }}</p>
		                    
		                    <a href="{% url 'restaurant:restaurant_detail' r.id %}" class="btn btn-danger">
		                        <span class="glyphicon glyphicon-cutlery"></span> {% trans "View the menu" %}
		                    </a>
	                    </div>
	                </div>
                {% empty %}
                
                <div id="no-restaurants">
                    <h2>{% trans "Sorry no restaurant found in your area :(" %}</h2>
                </div>
                {% endfor %}
                
            </div>
            
            <ul id="pagination" class="pagination-sm"></ul>
        </div>
    </div>
</div>
{% endblock %}

{% block page-scripts %}
<script type="text/javascript">
$(document).ready(function() {
	RegionSelector.init("#filterForm #id_country", "#filterForm #id_region");
	
	$('#pagination').twbsPagination({
		totalPages: {{ paginator.num_pages }},
		startPage: {{ page.number }},
		visiblePages: 10,
		first: '{% trans "First" %}',
		prev: '{% trans "Before" %}',
		next: '{% trans "Next" %}',
		last: '{% trans "Last" %}',
		onPageClick: function (event, page) {
	    	$.get("{% url 'restaurant:restaurant_list' %}?p="+page, function( data ) {
				var content = $('#restaurants', data).html();
				$('#restaurants').html(content);
			});
		}
	});
});
</script>
{% endblock %}

templates/restaurant/update.html
{% extends "accounts/dashboard.html" %}
{% load crispy_forms_tags i18n %}

{% block title %}{% trans "Update a restaurant" %}{% endblock %}

{% block content-pane %}
<div class="col-md-12">
    <form id="restaurant-form" method="post" enctype="multipart/form-data" action="{% url 'restaurant:restaurant_update' object.pk %}" >
        <h2 class="page-title">{% trans "Update the restaurant" %}</h2>
        {% csrf_token %}
        {% crispy form %}
        <button type="submit" id="form-submit-btn" class="btn btn-primary">
            <span class="fa fa-check"></span> {% trans "Save" %}
        </button>
    </form>
</div>
{% endblock %}

{% block page-scripts %}
<script type="text/javascript">
$(document).ready(function() {
	RegionSelector.init("#restaurant-form #id_country", "#restaurant-form #id_region");
});
</script>
{% endblock %}