modules/accounts/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
import views
import restaurateur_views

urlpatterns = patterns('',
    url(r'^register/$', views.RegisterView.as_view(), name="register"),
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name="logout"),
    
    url(r'^manage/$', views.ManagerView.as_view(), name="manage_account"),
    url(r'^dashboard/$', views.DashboardView.as_view(), name="dashboard"),
    url(r'^delete/(?P<pk>\d+)/$', views.DeleteUserView.as_view(), name="delete_account"),
    
    url(r'^restaurateurs/create/$', restaurateur_views.CreateRestaurateurView.as_view(), name="restaurateurs_create"),
    url(r'^restaurateurs/(?P<pk>\d+)/manage/$', restaurateur_views.ManageRestaurateurView.as_view(), name="restaurateurs_manage"),
    url(r'^restaurateurs/(?P<pk>\d+)/delete/$', restaurateur_views.DeleteRestaurateurView.as_view(), name="restaurateurs_delete"),
    url(r'^restaurateurs/list/$', restaurateur_views.RestaurateurListView.as_view(), name="restaurateurs_list"),
)

modules/restaurant/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from views import *

urlpatterns = patterns('',
    # Pour l'entrepreneur
    url(r'^create/$', RestaurantCreateView.as_view(), name="restaurant_create"),
    url(r'^(?P<pk>\d+)/update/$', RestaurantUpdateView.as_view(), name="restaurant_update"),
    url(r'^(?P<pk>\d+)/delete/$', RestaurantDeleteView.as_view(), name="restaurant_delete"),
    url(r'^list/$', RestaurantListView.as_view(), name="restaurant_list"),
    
    # Pour les restaurateurs
    url(r'^menus/create/$', MenuCreateView.as_view(), name="menu_create"),
    url(r'^menus/update/(?P<pk>\d+)$', MenuUpdateView.as_view(), name="menu_update"),
    url(r'^menus/list/$', MenuListView.as_view(), name="menu_list"),
    
    url(r'^meals/create/$', MealCreateView.as_view(), name="meal_create"),
    url(r'^meals/update/(?P<pk>\d+)$', MealUpdateView.as_view(), name="meal_update"),
    
    # Public
    url(r'^(?P<pk>\d+)/$', RestaurantDetailView.as_view(), name="restaurant_detail"),
    url(r'^$', RestaurantsView.as_view(), name="restaurants"),
)

urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.contrib import admin

import views

urlpatterns = patterns('',
	url(r'^$', views.HomeView.as_view(), name="home"),
	url(r'^admin/', include(admin.site.urls)), # Utile dans quelques rare cas
	url(r'^accounts/', include('accounts.urls', namespace="accounts")),
	url(r'^orders/', include('orders.urls', namespace="orders")),
    url(r'^restaurant/', include('restaurant.urls', namespace="restaurant")),
    url(r'^select_language/(?P<lang_code>\w+)/$', views.SelectLanguageView.as_view(), name="select_language"),
    url(r'^about/', views.TemplateView.as_view(template_name="about.html"), name="about"),
    url(r'^webservice/', include('webservice.urls', namespace="webservice")),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/about.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "About" %}{% endblock %}

{% block content %}
<div class="col-md-12">
    <div class="page-header">
        <h1>{% trans "LOG210 Laboratory - TEAM #5 - GROUP 3" %} <small> {% trans "SUMMER 2015" %}</small></h1>
    </div>
    
    <div class="col-md-6">
	    <div class="panel panel-default">
	        <div class="panel-heading">
	        	<span>MADE BY</span>
	        </div>
	        
	        <div class="panel-body">
	            <ul class="noStyle no-paddingLeft no-marginLeft">
	                <li>{% trans "André Koolen" %}</li>
	                <li>{% trans "Anthony Martin Coallier" %}</li>
	                <li>{% trans "Dominic Roberge" %}</li>
	            </ul>
	        </div>
	    </div>
	</div>
	
	<div class="col-md-6">
    	<div class="panel panel-default">
        	<div class="panel-heading">
        		<span>MADE FOR</span>
        	</div>
        	
        	<div class="panel-body">
            	<span>{% trans "École de technologie supérieure" %}</span><br>
                <span>{% trans "Department of Software Engineering and IT" %}</span><br>
                <span>{% trans "Classe : LOG210 - Analysis and software design" %}</span><br>
                <span>{% trans "Delivery date : 2015-07-27" %}</span><br>
        	</div>
    	</div>
    </div>
</div>
{% endblock %}

templates/base.html
{% load headerlogin i18n %}<!DOCTYPE HTML>
<html>
	<head>
		<meta charset="utf-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
		<meta name="viewport" content="width=device-width, initial-scale=1"/>
		<title>{% block title %}{% endblock %}{% trans " - Chemiresto" %}</title>
		{% block meta %}{% endblock %}
		<link href="{{ STATIC_URL }}bootstrap/css/bootstrap.min.css" rel="stylesheet"/>
		<link href="{{ STATIC_URL }}font-awesome/css/font-awesome.css" rel="stylesheet"/>
		<link href="{{ STATIC_URL }}css/style.css" rel="stylesheet"/>
		<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
		{% block head %}{% endblock %}
	</head>
	<body>
		<div id="holder">
			<header id="page-header">
				<div class="container">
					<div class="row">
						<div class="col-md-3">
							<h1 class="hidden-xs"><a href="{% url 'home' %}">{% trans "Chemiresto" %}</a></h1>
						</div>
						
						<nav id="navbar" class="col-md-4 navbar navbar-default">
							<div class="container-fluid">
								<div class="navbar-header">
									
									<h2 class="visible-xs no-marginTop marginLeft15"><a class="navbar-brand" href="#">{% trans "Chemiresto" %}</a></h2>
								</div>
								<div class="text-center navbar-collapse" id="collapse-navigation">
									<ul class="nav navbar-nav">
	
										{% if not request.user_details or request.user_details.is_a_client %}
											<li><a href="{% url 'restaurant:restaurants' %}"><span class="fa fa-cutlery"></span> {% trans "Restaurants" %}</a></li>
										{% endif %}
										
										{% if request.user_details %}
											<li><a href="{% url 'accounts:dashboard' %}"><span class="fa fa-tachometer"></span> {% trans "My dashboard" %}</a></li>
										{% endif %}
	
									</ul>
								</div>
							</div>
						</nav>
						
						{% block header-login %}{% headerlogin request %}{% endblock %}
					</div>
				</div>
				
				<div id="banner">
					<div class="container">
						{% if request.user.is_authenticated %}
							<div class="pull-right">
								<p class="no-marginBottom pull-right">{% trans "You are logged as" %} <strong>{{ request.user.email }}</strong></p>
							</div>
						{% endif %}	
					</div>
				</div>
			</header>
			
			<div id="page-content" class="container">
				{% if messages %}
					<div id="messages" class="row">
		                <div class="col-md-12">
	                        {% for message in messages %}
	                            <div class="alert alert-{{ message.tags }}">
	                                <a class="close" data-dismiss="alert">×</a>
	                                {{ message|safe }}
	                            </div>
	                        {% endfor %}
		                </div>
					</div>
	            {% endif %}
	            
	            <div class="row">
					{% block content %}
					{% endblock %}
	             </div>
			</div>
			
			<div id="page-footer">
				<div class="container">
					<div class="row">
						<nav>
							<ul>
								<li class="firstChild">
									<a href="{% url 'home' %}"><strong>{% trans "Chemiresto" %}</strong></a>
								</li>
		                        {#<li><a href="{% url 'restaurant:restaurants_list' %}">{% trans "Restaurants" %}</a></li>#}
								<li><a href="{% url 'about' %}">{% trans "About" %}</a></li>
							</ul>
						</nav>
						<p>{% trans "Copyright Chemiresto" %} &copy; {% trans "all rights reserved" %}</p>
					</div>
				</div>
			</div>
		</div>
		
		<script type="text/javascript" src="{{ STATIC_URL }}js/jquery-2.1.1.min.js"></script>
		<script type="text/javascript" src="{{ STATIC_URL }}bootstrap/js/bootstrap.min.js"></script>
		<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.twbsPagination.min.js"></script>
		<script type="text/javascript" src="{{ STATIC_URL }}js/app.js"></script>
		{% block page-scripts %}{% endblock %}
	</body>
</html>

templates/email.html
{% load i18n %}<style type="text/css">
a {
  color: red;
}

@media screen and (max-width: 480px){
	table {
		width: 100% !important;
	}
}
</style>

<table border="0" cellpadding="0" cellspacing="0" style="width:100%;">
	<tr>
		<td style="background-color:#CCCCCC;text-align:center;">	
			<table border="0" cellpadding="0" align='center' cellspacing="0" style="max-width:640px;border:1px solid #333;margin:15px auto;" width="640">
				<tr>
					<td style="color:white;border-bottom:3px solid #333;background:#f32837;">
						<table cellpadding='0' cellspacing='0' border='0' style='width:100%;'>
							<tr>
								<td colspan='3' style='height:15px;'></td>
							</tr>
							<tr>
								<td style='width:15px;'></td>
								<td>
									<table cellpadding='0' cellspacing='0' border='0' style='width:100%;'>
										<tr>
											<td>
												<h1 style="font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#ffffff; font-size:30px; margin:0; padding:0px;">Chemiresto</h1>
											</td>
											{% block email-header %}
											{% endblock %}
										</tr>
									</table>	
								</td>
								<td style='width:15px;'></td>
							</tr>
							<tr>
								<td colspan='3' style='height:15px;'></td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td style="color:#000000; background:#ffffff; display:block;">
						{% block email-content %}{% endblock %}
					</td>
				</tr>
				<tr>
					<td style="background:#f32837; height:10px; border-top:solid 1px #000000;"></td>
				</tr>
			</table>
		</td>
	</tr>
</table>

templates/register.html
{% extends "base.html" %}

{% block content %}
Register
{% endblock %}

templates/select_language.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Select your language" %}{% endblock %}

{% block content %}
<div class="col-md-12">
    <div class="page-header">
        <h1>{% trans "Select your language" %}</h1>
    </div>
    
    {% get_language_info_list for LANGUAGES as languages %}
    
    {% for language in languages %}
        <ul>
            <li>
                <a href="{% url 'select_language' language.code %}">{{ language.name_local }} ({{ language.code }})</a>
            </li>
        </ul>
    {% endfor %}
</div>
{% endblock %}